//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_tbl()
        {
            this.Ownership_person_tbl = new HashSet<Ownership_person_tbl>();
        }
    
        public int Id { get; set; }
        public string Company_name { get; set; }
        public string Trade_name { get; set; }
        public string Trade_feacher { get; set; }
        public string Trade_RegNo { get; set; }
        public Nullable<int> Currency_code { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> Country_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> Town_id { get; set; }
        public string Street_name { get; set; }
        public string Building_name { get; set; }
        public Nullable<int> Country2_id { get; set; }
        public Nullable<int> City2_id { get; set; }
        public Nullable<int> Town2_id { get; set; }
        public string Street2_name { get; set; }
        public string Building2_name { get; set; }
        public string Tel_no { get; set; }
        public string Jawal_no { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public Nullable<System.DateTime> Trade_start_date { get; set; }
        public string Licensed_operator_no { get; set; }
        public Nullable<double> Tax_aded { get; set; }
        public Nullable<double> Tax_income { get; set; }
        public Nullable<int> Ownership_kind_id { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> Calendar_id { get; set; }
        public Nullable<int> Financial_year { get; set; }
        public Nullable<System.DateTime> Financial_start_date { get; set; }
        public Nullable<System.DateTime> Financial_end_date { get; set; }
    
        public virtual Calender_tbl Calender_tbl { get; set; }
        public virtual City_tbl City_tbl { get; set; }
        public virtual City_tbl City_tbl1 { get; set; }
        public virtual Currency_tbl Currency_tbl { get; set; }
        public virtual Ownership_kind_tbl Ownership_kind_tbl { get; set; }
        public virtual Country_tbl Country_tbl { get; set; }
        public virtual Country_tbl Country_tbl1 { get; set; }
        public virtual Town_tbl Town_tbl { get; set; }
        public virtual Town_tbl Town_tbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ownership_person_tbl> Ownership_person_tbl { get; set; }
    }
}
