//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_tbl()
        {
            this.Sales_person_tbl = new HashSet<Sales_person_tbl>();
        }
    
        public int Id { get; set; }
        public string Customer_display_name { get; set; }
        public Nullable<int> Customer_activ_id { get; set; }
        public string Customer_first_name { get; set; }
        public string Customer_last_name { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Mobile { get; set; }
        public string Customer_payment_terms { get; set; }
        public Nullable<int> Currency_id { get; set; }
        public string Customer_Notes { get; set; }
        public string Customer_Website { get; set; }
        public Nullable<int> Country_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> Town_id { get; set; }
        public string Street_name { get; set; }
        public string Fax { get; set; }
        public string Facebook { get; set; }
        public Nullable<int> project_id { get; set; }
        public string Twitter { get; set; }
        public Nullable<double> Opining_balance { get; set; }
        public Nullable<int> Payment_preferred_id { get; set; }
    
        public virtual City_tbl City_tbl { get; set; }
        public virtual Country_tbl Country_tbl { get; set; }
        public virtual Payment_method_tbl Payment_method_tbl { get; set; }
        public virtual Project_tbl Project_tbl { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
        public virtual Town_tbl Town_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_person_tbl> Sales_person_tbl { get; set; }
    }
}
