//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Purchase_order
    {
        public int Id { get; set; }
        public Nullable<int> Purchase_order_id { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public Nullable<int> Store_id { get; set; }
        public string Delivery_note { get; set; }
        public string Delivery_tirms_conditions { get; set; }
        public string Delivery_recipient { get; set; }
    
        public virtual Store_tbl Store_tbl { get; set; }
    }
}
