//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_tbl
    {
        public int Id { get; set; }
        public string Emp_name { get; set; }
        public string Emp_pass { get; set; }
        public Nullable<int> Emp_work_id { get; set; }
        public Nullable<int> Store_id { get; set; }
        public byte[] Emp_seg { get; set; }
        public byte[] Emp_pic { get; set; }
        public Nullable<bool> t1 { get; set; }
        public Nullable<bool> t2 { get; set; }
        public Nullable<bool> t3 { get; set; }
        public Nullable<bool> t4 { get; set; }
        public Nullable<bool> t5 { get; set; }
        public Nullable<bool> t6 { get; set; }
        public Nullable<bool> t7 { get; set; }
        public Nullable<bool> t8 { get; set; }
        public Nullable<bool> t9 { get; set; }
        public Nullable<bool> t10 { get; set; }
        public Nullable<bool> t101 { get; set; }
        public Nullable<bool> t102 { get; set; }
        public Nullable<bool> t103 { get; set; }
        public Nullable<bool> t104 { get; set; }
        public Nullable<bool> t105 { get; set; }
        public Nullable<bool> t106 { get; set; }
        public Nullable<bool> t107 { get; set; }
        public Nullable<bool> t108 { get; set; }
        public Nullable<bool> t109 { get; set; }
        public Nullable<bool> t1010 { get; set; }
        public Nullable<bool> t1011 { get; set; }
        public Nullable<bool> t1012 { get; set; }
        public Nullable<bool> t1013 { get; set; }
        public Nullable<bool> t1014 { get; set; }
        public Nullable<bool> t1015 { get; set; }
        public Nullable<bool> t1016 { get; set; }
        public Nullable<bool> t1017 { get; set; }
        public Nullable<bool> t1018 { get; set; }
        public Nullable<bool> t1019 { get; set; }
        public Nullable<bool> t1020 { get; set; }
        public Nullable<bool> t1021 { get; set; }
        public Nullable<bool> t1022 { get; set; }
        public Nullable<bool> t1023 { get; set; }
        public Nullable<bool> t1024 { get; set; }
        public Nullable<bool> t1025 { get; set; }
        public Nullable<bool> t1026 { get; set; }
        public Nullable<bool> t1027 { get; set; }
        public Nullable<bool> t1028 { get; set; }
        public Nullable<bool> t1029 { get; set; }
        public Nullable<bool> t1030 { get; set; }
    
        public virtual Emp_work_tbl Emp_work_tbl { get; set; }
        public virtual Store_tbl Store_tbl { get; set; }
    }
}
