//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment_tbl
    {
        public int Id { get; set; }
        public Nullable<int> Sales_invoice_id { get; set; }
        public Nullable<System.DateTime> Installment_date { get; set; }
        public Nullable<System.DateTime> Installment_start_date { get; set; }
        public Nullable<int> Installment_number { get; set; }
        public Nullable<System.DateTime> Installment_due_date { get; set; }
        public string Installment_currency { get; set; }
        public Nullable<double> Currency_exchange { get; set; }
        public Nullable<double> Installment_due_amount { get; set; }
        public string Guarantor_name { get; set; }
        public string Guarantor_id_no { get; set; }
        public string kembyala_number { get; set; }
        public Nullable<int> Cash_hold_acc_a { get; set; }
        public Nullable<int> Cash_hold_acc_b { get; set; }
        public Nullable<int> Cash_hold_acc_c { get; set; }
        public Nullable<int> Cash_hold_acc_d { get; set; }
    
        public virtual Acc_a Acc_a { get; set; }
        public virtual Acc_b Acc_b { get; set; }
        public virtual Acc_c Acc_c { get; set; }
        public virtual Acc_d Acc_d { get; set; }
        public virtual Sales_invoice_tbl Sales_invoice_tbl { get; set; }
    }
}
