//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_kind_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_kind_tbl()
        {
            this.Items_tbl = new HashSet<Items_tbl>();
        }
    
        public int Id { get; set; }
        public string Item_kind_name { get; set; }
        public Nullable<int> Item_tax_id { get; set; }
        public Nullable<int> Decount_type_id { get; set; }
    
        public virtual Descount_type_tbl Descount_type_tbl { get; set; }
        public virtual Tax_type_tbl Tax_type_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_tbl> Items_tbl { get; set; }
    }
}
