//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_content_tbl
    {
        public int Id { get; set; }
        public Nullable<int> Items_id { get; set; }
        public string Content_name { get; set; }
    
        public virtual Items_tbl Items_tbl { get; set; }
    }
}
