//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items_tbl()
        {
            this.Item_content_tbl = new HashSet<Item_content_tbl>();
            this.Purchase_order_items_tbl = new HashSet<Purchase_order_items_tbl>();
            this.Sales_Estimate_items_tbl = new HashSet<Sales_Estimate_items_tbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Store_id { get; set; }
        public Nullable<int> Item_kind_id { get; set; }
        public string Item_name { get; set; }
        public string Item_description { get; set; }
        public Nullable<int> Item_content_id { get; set; }
        public Nullable<double> Item_quantity { get; set; }
        public Nullable<int> Item_unit_id { get; set; }
        public Nullable<double> Item_price_sell { get; set; }
        public Nullable<int> Item_sales_acc_a_id { get; set; }
        public Nullable<int> Item_sales_acc_b_id { get; set; }
        public Nullable<int> Item_sales_acc_c_id { get; set; }
        public Nullable<int> Item_sales_acc_d_id { get; set; }
        public Nullable<int> Item_purchase_acc_a_id { get; set; }
        public Nullable<int> Item_purchase_acc_b_id { get; set; }
        public Nullable<int> Item_purchase_acc_c_id { get; set; }
        public Nullable<int> Item_purchase_acc_d_id { get; set; }
        public Nullable<double> Item_point_reorder { get; set; }
        public Nullable<int> Cost_sold_goods_acc_a_id { get; set; }
        public Nullable<int> Cost_sold_goods_acc_b_id { get; set; }
        public Nullable<int> Cost_sold_goods_acc_c_id { get; set; }
        public Nullable<int> Cost_sold_goods_acc_d_id { get; set; }
        public string Item_feacher_color { get; set; }
        public Nullable<double> Barcode { get; set; }
    
        public virtual Acc_a Acc_a { get; set; }
        public virtual Acc_a Acc_a1 { get; set; }
        public virtual Acc_a Acc_a2 { get; set; }
        public virtual Acc_b Acc_b { get; set; }
        public virtual Acc_b Acc_b1 { get; set; }
        public virtual Acc_b Acc_b2 { get; set; }
        public virtual Acc_c Acc_c { get; set; }
        public virtual Acc_c Acc_c1 { get; set; }
        public virtual Acc_c Acc_c2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_content_tbl> Item_content_tbl { get; set; }
        public virtual Item_kind_tbl Item_kind_tbl { get; set; }
        public virtual Store_tbl Store_tbl { get; set; }
        public virtual Unit_tbl Unit_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_order_items_tbl> Purchase_order_items_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Estimate_items_tbl> Sales_Estimate_items_tbl { get; set; }
    }
}
