//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ownership_person_tbl
    {
        public int Id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Person_name { get; set; }
        public string Person_father { get; set; }
        public string Person_family { get; set; }
        public string Person_id { get; set; }
    
        public virtual Company_tbl Company_tbl { get; set; }
    }
}
