//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_invoice_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_invoice_tbl()
        {
            this.Purchase_payment_cheque_tbl = new HashSet<Purchase_payment_cheque_tbl>();
        }
    
        public int Id { get; set; }
        public string Vendor_name { get; set; }
        public string Vendor_tax_num { get; set; }
        public string Branch_name { get; set; }
        public Nullable<int> Purchase_invoice_number { get; set; }
        public Nullable<int> Purchase_order_id { get; set; }
        public Nullable<System.DateTime> Purchase_invoice_date { get; set; }
        public string Purchase_invoice_due_date { get; set; }
        public string Invoice_status { get; set; }
        public Nullable<bool> Is_invoice_taxable { get; set; }
        public Nullable<double> Invoice_amount_before_tax { get; set; }
        public Nullable<double> Invoice_level_tax { get; set; }
        public string Invoice_level_tax_type { get; set; }
        public Nullable<double> Invoice_level_tax_percent { get; set; }
        public Nullable<double> Invoice_amount_after_tax { get; set; }
        public string Invoice_note { get; set; }
        public string Invoice_tirms_conditions { get; set; }
        public Nullable<int> Payment_method_id { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<int> acc_a_id { get; set; }
        public Nullable<int> acc_b_id { get; set; }
        public Nullable<int> acc_c_id { get; set; }
        public Nullable<int> acc_d_id { get; set; }
        public Nullable<double> Debit_amount { get; set; }
        public Nullable<double> Cheque_amount { get; set; }
        public Nullable<double> Received_payment { get; set; }
    
        public virtual Acc_a Acc_a { get; set; }
        public virtual Acc_b Acc_b { get; set; }
        public virtual Acc_c Acc_c { get; set; }
        public virtual Acc_d Acc_d { get; set; }
        public virtual Payment_method_tbl Payment_method_tbl { get; set; }
        public virtual Purchase_order_tbl Purchase_order_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_payment_cheque_tbl> Purchase_payment_cheque_tbl { get; set; }
    }
}
