//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_payment_cheque_tbl
    {
        public int Id { get; set; }
        public Nullable<int> Purchase_invoice_id { get; set; }
        public string Cheque_num { get; set; }
        public Nullable<double> Cheque_amount { get; set; }
        public Nullable<System.DateTime> Cheque_due_date { get; set; }
        public string Bank_name { get; set; }
        public string Name_hold_cheque { get; set; }
        public string Cheque_currency { get; set; }
        public Nullable<double> Currency_exchange { get; set; }
    
        public virtual Purchase_invoice_tbl Purchase_invoice_tbl { get; set; }
    }
}
