//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_order_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_order_tbl()
        {
            this.Purchase_invoice_tbl = new HashSet<Purchase_invoice_tbl>();
            this.Purchase_order_items_tbl = new HashSet<Purchase_order_items_tbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Vendor_id { get; set; }
        public Nullable<System.DateTime> Purchase_order_date { get; set; }
        public Nullable<System.DateTime> Purchase_order_expert_date { get; set; }
        public Nullable<int> Project_id { get; set; }
        public Nullable<int> Purchase_order_status_id { get; set; }
        public Nullable<int> Currency_id { get; set; }
        public Nullable<double> Exchange_rate { get; set; }
        public Nullable<double> Purchase_order_amount_before_tax { get; set; }
        public Nullable<double> Purchase_order_level_tax { get; set; }
        public string Purchase_order_level_tax_type { get; set; }
        public Nullable<double> Purchase_order_level_tax_percent { get; set; }
        public Nullable<double> Purchase_order_amount_after_tax { get; set; }
        public string Purchase_order_notes { get; set; }
        public string Purchase_order_terms_conditions { get; set; }
    
        public virtual Currency_tbl Currency_tbl { get; set; }
        public virtual Project_tbl Project_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_invoice_tbl> Purchase_invoice_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_order_items_tbl> Purchase_order_items_tbl { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
        public virtual Vendors_tbl Vendors_tbl { get; set; }
    }
}
