//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Receipt_payment_tbl
    {
        public int Id { get; set; }
        public string Customer_name { get; set; }
        public Nullable<int> Sales_invoice_id { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
        public string Payment_method { get; set; }
        public string currency { get; set; }
        public Nullable<double> Currency_exchange { get; set; }
        public Nullable<int> Cash_hold_acc_a { get; set; }
        public Nullable<int> Cash_hold_acc_b { get; set; }
        public Nullable<int> Cash_hold_acc_c { get; set; }
        public Nullable<int> Cash_hold_acc_d { get; set; }
        public string Amount_words { get; set; }
        public string Cheque_num { get; set; }
        public Nullable<System.DateTime> Cheque_due_date { get; set; }
        public string Bank_name { get; set; }
        public string Name_hold_cheque { get; set; }
    
        public virtual Acc_a Acc_a { get; set; }
        public virtual Acc_b Acc_b { get; set; }
        public virtual Acc_c Acc_c { get; set; }
        public virtual Acc_d Acc_d { get; set; }
        public virtual Sales_invoice_tbl Sales_invoice_tbl { get; set; }
    }
}
