//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Estimate_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Estimate_tbl()
        {
            this.Delivery_Sales_Estimate = new HashSet<Delivery_Sales_Estimate>();
            this.Sales_Estimate_items_tbl = new HashSet<Sales_Estimate_items_tbl>();
            this.Sales_invoice_tbl = new HashSet<Sales_invoice_tbl>();
        }
    
        public int Id { get; set; }
        public string Customer_name { get; set; }
        public Nullable<System.DateTime> Estimate_date { get; set; }
        public Nullable<System.DateTime> Estimate_expert_date { get; set; }
        public string Project_name { get; set; }
        public Nullable<int> Estimate_status_id { get; set; }
        public string Sails_person { get; set; }
        public Nullable<int> Currency_id { get; set; }
        public Nullable<double> Exchange_rate { get; set; }
        public Nullable<double> Sales_Estimate_amount_before_tax { get; set; }
        public Nullable<double> Sales_Estimate_level_tax { get; set; }
        public string Sales_Estimate_level_tax_type { get; set; }
        public Nullable<double> Sales_Estimate_level_tax_percent { get; set; }
        public Nullable<double> Purchase_order_amount_after_tax { get; set; }
        public Nullable<double> Shipping_charge { get; set; }
        public string Purchase_order_notes { get; set; }
        public string Purchase_order_terms_conditions { get; set; }
    
        public virtual Currency_tbl Currency_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Sales_Estimate> Delivery_Sales_Estimate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Estimate_items_tbl> Sales_Estimate_items_tbl { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_invoice_tbl> Sales_invoice_tbl { get; set; }
    }
}
