//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_invoice_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_invoice_tbl()
        {
            this.Installment_tbl = new HashSet<Installment_tbl>();
            this.Sales_Receipt_payment_tbl = new HashSet<Sales_Receipt_payment_tbl>();
        }
    
        public int Id { get; set; }
        public string Customer_name { get; set; }
        public Nullable<int> Sales_Estimate_id { get; set; }
        public string Branch_name { get; set; }
        public Nullable<int> Purchase_invoice_number { get; set; }
        public Nullable<System.DateTime> Sails_invoice_date { get; set; }
        public Nullable<System.DateTime> Sales_invoice_due_date { get; set; }
        public string Invoice_status { get; set; }
        public Nullable<bool> Is_invoice_taxable { get; set; }
        public Nullable<double> Invoice_amount_before_tax { get; set; }
        public Nullable<double> Invoice_level_tax { get; set; }
        public string Invoice_level_tax_type { get; set; }
        public Nullable<double> Invoice_level_tax_percent { get; set; }
        public Nullable<double> Invoice_amount_after_tax { get; set; }
        public Nullable<int> Sarvice_id { get; set; }
        public string Invoice_note { get; set; }
        public string Invoice_tirms_conditions { get; set; }
        public Nullable<int> Payment_method_id { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<int> acc_a_id { get; set; }
        public Nullable<int> acc_b_id { get; set; }
        public Nullable<int> acc_c_id { get; set; }
        public Nullable<int> acc_d_id { get; set; }
        public Nullable<double> Debit_amount { get; set; }
        public Nullable<double> Cheque_amount { get; set; }
        public Nullable<double> Installment_amount { get; set; }
        public Nullable<double> Received_payment { get; set; }
    
        public virtual Acc_a Acc_a { get; set; }
        public virtual Acc_b Acc_b { get; set; }
        public virtual Acc_c Acc_c { get; set; }
        public virtual Acc_d Acc_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment_tbl> Installment_tbl { get; set; }
        public virtual Payment_method_tbl Payment_method_tbl { get; set; }
        public virtual Sales_Estimate_tbl Sales_Estimate_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Receipt_payment_tbl> Sales_Receipt_payment_tbl { get; set; }
    }
}
