//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_person_tbl
    {
        public int Id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public string Sales_person_name { get; set; }
    
        public virtual Customer_tbl Customer_tbl { get; set; }
    }
}
