//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_prg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store_tbl()
        {
            this.Delivery_Purchase_order = new HashSet<Delivery_Purchase_order>();
            this.Emp_tbl = new HashSet<Emp_tbl>();
            this.Items_tbl = new HashSet<Items_tbl>();
            this.Purchase_order_items_tbl = new HashSet<Purchase_order_items_tbl>();
            this.Sales_Estimate_items_tbl = new HashSet<Sales_Estimate_items_tbl>();
        }
    
        public int Id { get; set; }
        public string Store_name { get; set; }
        public Nullable<int> Country_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> Town_id { get; set; }
        public string Street_name { get; set; }
        public string Building_name { get; set; }
    
        public virtual City_tbl City_tbl { get; set; }
        public virtual Country_tbl Country_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Purchase_order> Delivery_Purchase_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_tbl> Emp_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_tbl> Items_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_order_items_tbl> Purchase_order_items_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Estimate_items_tbl> Sales_Estimate_items_tbl { get; set; }
        public virtual Town_tbl Town_tbl { get; set; }
    }
}
